import { importCalWorkbook } from './importers/calImporter.js';
import { loadTransactions,saveTransactions,mergeTransactions,loadPreferences,savePreferences,clearAll } from './services/storage.js';
import { analyze } from './services/insights.js';
const app=document.querySelector('#app');let transactions=loadTransactions(),prefs=loadPreferences();
const money=n=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:0}).format(n||0);
const labels={essential:'הכרחי',optimizable:'חשוב · אפשר לייעל',discretionary:'בשליטתי',review:'לטיפול'};
const icons={essential:'✓',optimizable:'↘',discretionary:'◎',review:'?'};
const monthName=m=>m?new Intl.DateTimeFormat('he-IL',{month:'long',year:'numeric'}).format(new Date(m+'-01T00:00:00')):'';
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){const a=analyze(transactions,prefs);app.innerHTML=`<main class="shell"><header class="top"><div><div class="eyebrow">הכסף שלך, בתמונה אחת</div><h1>כמה יצא?</h1><p>${a.current?monthName(a.current):'מעלים קובץ אחד ומתחילים.'}</p></div><button id="settings" class="iconbtn" title="תקציבים">⚙︎</button></header>
<section id="drop" class="upload"><input id="file" type="file" accept=".xlsx,.xls" hidden><div class="uploadIcon">↑</div><div><strong>העלאת פירוט אשראי</strong><p>גרור לכאן Excel של כאל או בחר קובץ. הנתונים נשארים בדפדפן שלך.</p></div><button id="pick" class="btn primary">בחירת קובץ</button><div id="status" class="status"></div></section>
${transactions.length?dashboard(a):`<section class="empty card"><div class="bigicon">◌</div><h2>עוד אין מה למדוד</h2><p>אחרי העלאת הקובץ אארגן את ההוצאות ואציע סיווג ראשוני. לא צריך להגדיר הכול מראש.</p></section>`}
<div id="drawer" class="drawer hidden"></div></main>`;bind(a)}
function dashboard(a){const discBudget=a.budgetRows.reduce((s,x)=>s+x.amount,0);const disc=a.byControl.discretionary;const pct=discBudget?Math.round(disc/discBudget*100):0;return `<section class="hero card"><div><span class="kicker">הוצאות שבשליטתך</span><strong>${money(disc)}</strong><p>${discBudget?`מתוך מסגרת חודשית בסיסית של ${money(discBudget)}`:'עדיין לא הגדרת תקציבים'}</p></div><div class="ring" style="--p:${Math.min(100,pct)}"><div><b>${pct}%</b><span>מהמסגרת</span></div></div></section>
<section class="grid metrics"><button class="card metric clickable" data-open="essential"><span>הכרחי</span><b>${money(a.byControl.essential)}</b><small>נספר בסך הכול, לא יעד לצמצום</small></button><button class="card metric clickable" data-open="optimizable"><span>אפשר לייעל</span><b>${money(a.byControl.optimizable)}</b><small>${a.opt.length} חיובים לבדיקה</small></button><button class="card metric clickable" data-open="review"><span>לטיפול</span><b>${a.review.length}</b><small>האפליקציה לא בטוחה לגביהם</small></button></section>
<section class="card section"><div class="sectionHead"><div><span class="kicker">היעדים שלך</span><h2>תקציבים</h2></div><button id="editBudgets" class="textbtn">עריכה</button></div><div class="budgetList">${a.budgetRows.map(b=>budgetRow(b)).join('')}</div></section>
<section class="split section"><div class="card"><span class="kicker">מבט רחב</span><h2>ששת החודשים האחרונים</h2>${trend(a)}</div><div class="card"><span class="kicker">תובנות</span><h2>מה כדאי לדעת</h2><div class="insights">${a.insights.map(x=>`<div class="insight"><i>✦</i><span>${x}</span></div>`).join('')||'<p class="muted">ככל שתעלה עוד חודשים, התמונה כאן תהיה חכמה יותר.</p>'}</div></div></section>
<details class="card section"><summary><div><span class="kicker">כשבא לך לצלול</span><h2>כל העסקאות</h2></div><span class="chev">⌄</span></summary><div class="transactions">${a.cur.map(t=>txRow(t)).join('')}</div></details>
<footer><button id="clear" class="dangerlink">מחיקת כל הנתונים המקומיים</button></footer>`}
function budgetRow(b){const p=Math.min(100,Math.max(0,b.pct));return `<div class="budget"><div class="budgetTop"><div><b>${escapeHtml(b.name)}</b><small>${b.mode==='rollover'?'תקציב מצטבר':'תקציב חודשי'} · ממוצע 6 חודשים ${money(b.sixAvg)}</small></div><div class="budgetNum"><b>${money(b.spent)}</b><span> / ${money(b.amount)}</span></div></div><div class="progress"><i style="width:${p}%" class="${b.pct>100?'over':''}"></i></div><div class="budgetFoot ${b.remaining<0?'bad':'good'}">${b.remaining>=0?`${money(b.remaining)} נשארו במסגרת`:`חריגה של ${money(Math.abs(b.remaining))}`}</div></div>`}
function trend(a){if(!a.trend.length)return '<p class="muted">צריך עוד נתונים.</p>';const max=Math.max(...a.trend.map(x=>x.discretionary),1);return `<div class="chart">${a.trend.map(x=>`<div class="col"><div class="colbar" style="height:${Math.max(5,x.discretionary/max*120)}px"></div><b>${money(x.discretionary)}</b><span>${x.month.slice(5)}</span></div>`).join('')}</div><p class="muted">העמודות מציגות רק הוצאות שסומנו ״בשליטתי״, כדי שהרעש של הוצאות קבועות לא יסתיר את ההתנהלות.</p>`}
function txRow(t){return `<div class="tx"><div class="txMain"><b>${escapeHtml(t.merchant)}</b><span>${escapeHtml(t.category)} · ${new Date(t.date+'T00:00:00').toLocaleDateString('he-IL')}</span></div><div class="txRight"><b>${money(t.amount)}</b><button class="tag ${t.control}" data-merchant="${encodeURIComponent(t.merchant)}">${icons[t.control]} ${labels[t.control]}</button></div></div>`}
function bind(a){const input=document.querySelector('#file'),drop=document.querySelector('#drop'),status=document.querySelector('#status');document.querySelector('#pick').onclick=()=>input.click();input.onchange=()=>input.files[0]&&handle(input.files[0],status);['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>e.dataTransfer.files[0]&&handle(e.dataTransfer.files[0],status));document.querySelectorAll('.tag').forEach(x=>x.onclick=()=>openMerchant(decodeURIComponent(x.dataset.merchant)));document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openClass(x.dataset.open,a));document.querySelector('#settings').onclick=()=>openBudgets();document.querySelector('#editBudgets')?.addEventListener('click',openBudgets);document.querySelector('#clear')?.addEventListener('click',()=>{if(confirm('למחוק את כל הנתונים וההגדרות ששמורים בדפדפן?')){clearAll();transactions=[];prefs=loadPreferences();render()}})}
function showDrawer(html){const d=document.querySelector('#drawer');d.innerHTML=`<div class="shade" data-close></div><aside><button class="close" data-close>×</button>${html}</aside>`;d.classList.remove('hidden');d.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>d.classList.add('hidden'))}
function openMerchant(merchant){const rule=prefs.merchantRules[merchant]||{};showDrawer(`<span class="kicker">סיווג קבוע</span><h2>${escapeHtml(merchant)}</h2><p class="muted">הבחירה תיזכר גם בקבצים הבאים שבהם יופיע אותו בית עסק.</p><div class="choices">${Object.entries(labels).map(([k,v])=>`<button data-class="${k}" class="choice ${rule.control===k?'selected':''}"><b>${icons[k]} ${v}</b><small>${k==='essential'?'הוצאה שצריך לחיות איתה':k==='optimizable'?'צריך אותה, אבל אולי אפשר לשלם פחות':k==='discretionary'?'כאן תקציב והרגלים באמת משנים':'אשאיר אותה ברשימת הדברים לבדיקה'}</small></button>`).join('')}</div><label>תקציב משויך<select id="group"><option value="">ללא</option>${Object.keys(prefs.budgets).map(x=>`<option ${rule.budgetGroup===x?'selected':''}>${escapeHtml(x)}</option>`).join('')}</select></label>`);document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{prefs.merchantRules[merchant]={...prefs.merchantRules[merchant],control:b.dataset.class,budgetGroup:document.querySelector('#group').value};savePreferences(prefs);render()});document.querySelector('#group').onchange=e=>{prefs.merchantRules[merchant]={...prefs.merchantRules[merchant],budgetGroup:e.target.value};savePreferences(prefs)}}
function openClass(cls,a){const rows=a.cur.filter(t=>t.control===cls);showDrawer(`<span class="kicker">${labels[cls]}</span><h2>${rows.length} עסקאות</h2><div class="transactions">${rows.map(txRow).join('')}</div>`);document.querySelectorAll('#drawer .tag').forEach(x=>x.onclick=()=>openMerchant(decodeURIComponent(x.dataset.merchant)))}
function openBudgets(){showDrawer(`<span class="kicker">היעדים שלך</span><h2>תקציבים</h2><p class="muted">חודשי מתאפס בכל חודש. מצטבר שומר את מה שלא השתמשת בו לרכישה גדולה בעתיד.</p><div id="budgetEdit">${Object.entries(prefs.budgets).map(([n,b])=>`<div class="budgetEdit"><input value="${escapeHtml(n)}" disabled><input data-amount="${encodeURIComponent(n)}" type="number" value="${b.amount}"><select data-mode="${encodeURIComponent(n)}"><option value="monthly" ${b.mode==='monthly'?'selected':''}>חודשי</option><option value="rollover" ${b.mode==='rollover'?'selected':''}>מצטבר</option></select></div>`).join('')}</div><button id="saveBudgets" class="btn primary wide">שמירה</button>`);document.querySelector('#saveBudgets').onclick=()=>{document.querySelectorAll('[data-amount]').forEach(x=>{const n=decodeURIComponent(x.dataset.amount);prefs.budgets[n].amount=Math.max(0,+x.value||0)});document.querySelectorAll('[data-mode]').forEach(x=>{const n=decodeURIComponent(x.dataset.mode);prefs.budgets[n].mode=x.value});savePreferences(prefs);render()}}
async function handle(file,status){try{status.className='status';status.textContent='קוראת ומארגנת…';const incoming=await importCalWorkbook(file);const before=transactions.length;transactions=mergeTransactions(transactions,incoming);saveTransactions(transactions);const added=transactions.length-before;render();const s=document.querySelector('#status');s.textContent=`✓ נקלטו ${incoming.length} עסקאות · ${added} חדשות`;s.className='status success'}catch(e){status.className='status error';status.textContent=e.message||'לא הצלחתי לקרוא את הקובץ.'}}
render();
